# Generated by Django 5.1.4 on 2025-01-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feature_delete_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='age',
            field=models.IntegerField(),
        ),
    ]
