# Generated by Django 5.1.4 on 2025-01-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_feature_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='height',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
