# Generated by Django 5.1.4 on 2025-01-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feature_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='height',
        ),
        migrations.AddField(
            model_name='feature',
            name='bloodtype',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
