# Generated by Django 5.1.5 on 2025-01-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_feature_height_feature_bloodtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feature',
        ),
    ]
